### ISSUE TITLE
Not seeing it installable in SBT3

### ISSUE THREAD

**Issue by ryancastro** [joeyespo/sublimetext-console-exec#2]
Probably because it's not compatible with Sublime Text 3. I'd love to see compatibility. :)

**Comment by joeyespo** [comment]
I would too! I haven't upgraded to ST3 yet though because the keyboard navigation was changed ([Build 3016](http://www.sublimetext.com/3dev)), and I don't have the time right now to re-learn them during my day-to-day.

Once they provide a way to switch back to ST2 bindings, or I finally bite the bullet and re-learn my arrow key habits, I'll switch to ST3 and upgrade this.

In the meantime, if anyone sends a PR, I'll happily accept.

**Comment by ramiabughazaleh** [comment]
I cloned the repository to my Sublime Text 3 packages folder and this package worked as expected (on Windows). I think it just needs to be added to packagecontrol.io as instructed here: https://packagecontrol.io/docs/submitting_a_package.

Thank you.

**Comment by joeyespo** [comment]
@ramiabughazaleh That's good news! Thanks for trying it out :-) 

Do you happen to know the new packagecontrol.io format? I'd be happy to submit. I'm just not ready to spend the time researching it yet to make sure it's installable on both ST2 and ST3.

**Comment by joeyespo** [comment]
Just added it to Package Control in https://github.com/wbond/package_control_channel/pull/4465. This should make it available in both ST3 and ST2 again once it's pulled in.

**Comment by joeyespo** [comment]
It was merged in!

Thanks for opening the issue @ryancastro, and for reminding me about this @ramiabughazaleh.
